Repository capitalone/Particle-Cloud-Framework, pull requests merged in 2019-03, with the labels that each got.

#44 Cross cloud storage
  docs/source/pcf.quasiparticle.cross_cloud.cross_cloud_storage.rst
  docs/source/pcf.quasiparticle.cross_cloud.rst
  docs/source/pcf.quasiparticle.rst
  docs/source/quasiparticlelist.rst
  examples/particle/gcp/use_storage/example_bucket.py
  examples/particle/gcp/use_storage/test.txt
  examples/quasiparticle/cross_cloud/README.MD
  examples/quasiparticle/cross_cloud/cross_cloud_storage.py
  examples/quasiparticle/cross_cloud/test.txt
  pcf/particle/gcp/storage/bucket.py
  pcf/quasiparticle/cross_cloud/__init__.py
  pcf/quasiparticle/cross_cloud/cross_cloud_storage/__init__.py
  pcf/quasiparticle/cross_cloud/cross_cloud_storage/cross_cloud_storage.py
Labels: new particle

#62 Set desired state with string
  docs/source/sections/quickstart.rst
  docs/source/sections/quickstartdeveloper.rst
  pcf/core/particle.py
  pcf/core/pcf_exceptions.py
  pcf/core/quasiparticle.py
  pcf/test/core/test_particle.py
Labels: enhancement

#57 Philosophy
  docs/source/index.rst
  docs/source/sections/philosophy.rst
Labels: documentation

#69 Azure bug
  setup.py
Labels: bug

#76 Subnet public
  pcf/particle/aws/vpc/subnet.py
Labels: enhancement

#78 Ecs task definition remove start param filters
  pcf/particle/aws/ecs/ecs_task_definition.py
Labels: enhancement
