Repository capitalone/Particle-Cloud-Framework, pull requests merged in 2019-04, with the labels that each got.

#82 0.4.1
  docs/source/index.rst
  docs/source/sections/philosophy.rst
  examples/quasiparticle/aws/jit/jit.py
  pcf/particle/aws/ecs/ecs_task_definition.py
  pcf/particle/aws/vpc/subnet.py
  setup.py
Labels: release

#66 Glacier Vault
  examples/particle/aws/glacier/use_glacier/README.md
  examples/particle/aws/glacier/use_glacier/example_glacier_vault.py
  pcf/particle/aws/glacier/__init__.py
  pcf/particle/aws/glacier/glacier_vault.py
  pcf/test/particle/aws/glacier/__init__.py
  pcf/test/particle/aws/glacier/replay/glacier.DeleteVault_1.json
  pcf/test/particle/aws/glacier/replay/glacier.DescribeVault_1.json
  pcf/test/particle/aws/glacier/replay/glacier.DescribeVault_2.json
  pcf/test/particle/aws/glacier/replay/glacier.DescribeVault_3.json
  pcf/test/particle/aws/glacier/replay/glacier.ListTagsForVault_1.json
  pcf/test/particle/aws/glacier/test_glacier_vault.py
Labels: new particle

#87 Updating Readme
  README.md
Labels: documentation
