Repository capitalone/Particle-Cloud-Framework, pull requests merged in 2019-02, with the labels that each got.

#34 Just in Time Infrastructure example
  examples/quasiparticle/aws/jit/README.md
  examples/quasiparticle/aws/jit/jit.py
  pcf/core/aws_resource.py
  pcf/util/pcf_util.py
  requirements.txt
Labels: bug, enhancement

#35 Flask app
  examples/flask_app/README.md
  examples/flask_app/app.py
  examples/flask_app/dockerfile
  examples/flask_app/pcf_example_config.json
  examples/flask_app/requirements.txt
  examples/quasiparticle/aws/simple_webapp/README.md
Labels: enhancement

#36 Auto generate test
  pcf/particle/aws/route53/hosted_zone.py
  pcf/particle/aws/sqs/sqs_queue.py
  pcf/test/particle/aws/test_particles.py
  pcf/test/particle/aws/testdata.json
Labels: enhancement

#38 Add CLI
  .coveragerc
  .gitignore
  Makefile
  docs/source/index.rst
  docs/source/sections/cli.rst
  pcf/__init__.py
  pcf/cli/__init__.py
  pcf/cli/cli.py
  pcf/cli/commands/__init__.py
  pcf/cli/commands/apply.py
  pcf/cli/commands/run.py
  pcf/cli/commands/stop.py
  pcf/cli/commands/terminate.py
  pcf/cli/utils.py
  pcf/particle/gcp/compute_engine/vm_instance.py
  pcf/test/cli/__init__.py
  pcf/test/cli/commands/test_apply.py
  pcf/test/cli/commands/test_run.py
  pcf/test/cli/commands/test_stop.py
  pcf/test/cli/commands/test_terminate.py
  pcf/test/cli/test_cli.py
  pcf/test/cli/test_utils.py
  pcf/test/conftest.py
  pcf/test/fixtures/bad.json
  pcf/test/fixtures/bad.yaml
  pcf/test/fixtures/bad.yml
  pcf/test/fixtures/custom.json
  pcf/test/fixtures/custom.yaml
  pcf/test/fixtures/custom.yml
  pcf/test/fixtures/no_flavor.yml
  pcf/test/fixtures/pcf.json
  pcf/test/fixtures/pcf.yaml
  pcf/test/fixtures/pcf.yml
  pcf/test/util/test_pcf_util.py
  pcf/util/pcf_util.py
  pytest.ini
  requirements.txt
  setup.py
Labels: new feature

#55 State mapping enum
  pcf/core/__init__.py
  pcf/test/particle/aws/test_particles.py
Labels: enhancement

#6 PCF Style Guide
  STYLEGUIDE.md
Labels: enhancement

#50 Jitidocs
  docs/source/concepts/concepts.rst
  docs/source/index.rst
  docs/source/sections/core.rst
  docs/source/sections/quickstart.rst
Labels: documentation

#59 quasiparticle logging type and message
  pcf/core/quasiparticle.py
Labels: enhancement

#45 Azure storage
  docs/source/particlelist.rst
  docs/source/pcf.cli.commands.rst
  docs/source/pcf.cli.rst
  docs/source/pcf.core.rst
  docs/source/pcf.extended_particles.aws.lambda_function.rst
  docs/source/pcf.extended_particles.aws.rst
  docs/source/pcf.extended_particles.rst
  docs/source/pcf.particle.azure.blob.rst
  docs/source/pcf.particle.gcp.compute_engine.rst
  examples/__init__.py
  examples/particle/__init__.py
  examples/particle/azure/__init__.py
  examples/particle/azure/blob/__init__.py
  examples/particle/azure/blob/use_blob_container/README.md
  examples/particle/azure/blob/use_blob_container/__init__.py
  examples/particle/azure/blob/use_blob_container/example_blob_container.py
  pcf/core/azure_resource.py
  pcf/particle/azure/blob/__init__.py
  pcf/particle/azure/blob/blob_container.py
  pcf/test/particle/azure/__init__.py
  pcf/test/particle/azure/blob/__init__.py
  pcf/test/particle/azure/blob/test_blob_container.py
  requirements.txt
Labels: new particle
