Repository capitalone/Particle-Cloud-Framework, pull requests merged in 2019-06, with the labels that each got.

#125 add fields to ecs_Service
  pcf/particle/aws/ecs/ecs_service.py
Labels: bug

#121 Add dynamodb tags
  examples/particle/aws/dynamodb/use_dynamodb/README.md
  examples/particle/aws/dynamodb/use_dynamodb/example_dynamodb_table.py
  pcf/particle/aws/dynamodb/dynamodb_table.py
  pcf/test/particle/aws/dynamodb/replay/dynamodb.CreateTable_1.json
  pcf/test/particle/aws/dynamodb/replay/dynamodb.DeleteTable_1.json
  pcf/test/particle/aws/dynamodb/replay/dynamodb.DescribeTable_1.json
  pcf/test/particle/aws/dynamodb/replay/dynamodb.DescribeTable_10.json
  pcf/test/particle/aws/dynamodb/replay/dynamodb.DescribeTable_2.json
  pcf/test/particle/aws/dynamodb/replay/dynamodb.DescribeTable_3.json
  pcf/test/particle/aws/dynamodb/replay/dynamodb.DescribeTable_4.json
  pcf/test/particle/aws/dynamodb/replay/dynamodb.DescribeTable_5.json
  pcf/test/particle/aws/dynamodb/replay/dynamodb.DescribeTable_6.json
  pcf/test/particle/aws/dynamodb/replay/dynamodb.DescribeTable_7.json
  pcf/test/particle/aws/dynamodb/replay/dynamodb.DescribeTable_8.json
  pcf/test/particle/aws/dynamodb/replay/dynamodb.DescribeTable_9.json
  pcf/test/particle/aws/dynamodb/replay/dynamodb.ListTagsOfResource_1.json
  pcf/test/particle/aws/dynamodb/replay/dynamodb.ListTagsOfResource_2.json
  pcf/test/particle/aws/dynamodb/replay/dynamodb.ListTagsOfResource_3.json
  pcf/test/particle/aws/dynamodb/replay/dynamodb.ListTagsOfResource_4.json
  pcf/test/particle/aws/dynamodb/replay/dynamodb.ListTagsOfResource_5.json
  pcf/test/particle/aws/dynamodb/replay/dynamodb.ListTagsOfResource_6.json
  pcf/test/particle/aws/dynamodb/replay/dynamodb.ListTagsOfResource_7.json
  pcf/test/particle/aws/dynamodb/replay/dynamodb.TagResource_1.json
  pcf/test/particle/aws/dynamodb/replay/dynamodb.UpdateTable_1.json
  pcf/test/particle/aws/dynamodb/test_dynamodb_table.py
  pcf/test/particle/aws/testdata.json
Labels: enhancement, new feature

#126 Alb fix
  pcf/particle/aws/ec2/alb/alb.py
Labels: bug

#129 Release 0.4.4
  docs/source/conf.py
  pcf/__init__.py
Labels: release
