Repository capitalone/Particle-Cloud-Framework, pull requests merged in 2019-05, with the labels that each got.

#54 Generate pcf config
  examples/tools/pcf_generator/README.md
  examples/tools/pcf_generator/example_pcf_generator.py
  pcf/core/quasiparticle.py
  pcf/tools/__init__.py
  pcf/tools/pcf_generator/__init__.py
  pcf/tools/pcf_generator/pcf_generator.py
Labels: new feature

#40 Add CI
  .gitignore
  .travis.yml
  Makefile
  README.md
  pcf/__init__.py
  requirements-dev.txt
  requirements.txt
  setup.py
  tasks.py
Labels: new feature

#112 Update the requirements, readme, and setup.py
  .travis.yml
  README.md
  pcf/particle/aws/ecs/ecs_cluster.py
  pcf/test/particle/aws/route53/test_route53_record.py
  pcf/test/quasiparticle/aws/test_ec2_route53.py
  pcf/test/util/aws/test_aws_lookup.py
  requirements-dev.txt
  requirements.txt
  setup.py
Labels: bug, work in progress

#114 Generated tests added cli functionality
  docs/source/sections/cont.rst
  pcf/core/pcf_exceptions.py
  pcf/test/particle/aws/generate_placebo.py
  pcf/test/particle/aws/test_particles.py
Labels: enhancement
